/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.Random;
/**
 *
 * @author WINDOWS 10
 */
public class Form_Registrasi extends javax.swing.JFrame {
    private int id;
    private int nim;
    private String nama;
    private String ttl;
    private String jenisKelamin;
    private String alamat;
    private String programStudi;
    private String kelas;
    String sql;
    java.sql.Connection conn;
    java.sql.PreparedStatement pstm;
    java.sql.ResultSet res;
    
    
    /**
     * Creates new form Form_Registrasi
     */
    public Form_Registrasi() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtTtl = new javax.swing.JTextField();
        txtalm = new javax.swing.JTextField();
        txtPs = new javax.swing.JTextField();
        btSimpan = new javax.swing.JButton();
        cbJK = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Form Register");

        jLabel2.setText("Nama");

        jLabel3.setText("Tempat, tanggal lahir");

        jLabel4.setText("Alamat");

        jLabel5.setText("Program Studi");

        jLabel7.setText("Jenis Kelamin");

        btSimpan.setText("Simpan");
        btSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });

        cbJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("<");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPs, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtalm, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTtl, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(btSimpan)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtTtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cbJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtalm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtPs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btSimpan)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int getId() {
        try
        {
            sql = "SELECT id_data FROM data_mahasiswa ORDER BY id_data DESC";
            conn =(Connection)Database.configDB();
            pstm = conn.prepareStatement(sql);
            res = pstm.executeQuery();
            
            if(res.next())
            {
                int Id = res.getInt(1);
                id = Id+1;
            }
        }
        catch(SQLException e){
            
        }
        
        return id;
    }
    
    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        simpanData();
    }//GEN-LAST:event_btSimpanActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
    Login login = new Login();
    login.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked
    
    private void emptyData()
    {
    txtnama.setText("");
    txtTtl.setText("");
    txtalm.setText("");
    txtPs.setText("");
    cbJK.setSelectedIndex(0);
       
    }
    //METHOD UNTUK BERPINDAH KE TAMPILAN GUI REGISTER
    public void toRegister()
    {
        Register reg = new Register();
        reg.setVisible(true);
        this.dispose();
    }
    
    private int getIncreaseNim()
    {
        int increaseNumber = 0;
        try{
            sql = "SELECT NIM FROM data_mahasiswa ORDER BY id_data DESC";
            conn =(Connection)Database.configDB()  ;                 //MENGKONEKSIKAN KEDATABASE DARI KELAS DATABASE METHOD CONFIGDB
            pstm = conn.prepareStatement(sql);                         //MEMBUAT STATEMENT MYSQL
            res = pstm.executeQuery();
            
            if(res.next())
            {
                int Nim = res.getInt(1);
                increaseNumber = Nim + 1;                
            }
        }
        catch(SQLException e)
        {
        }
        return increaseNumber;
    }
    
    private String getRandomClass()
    {
        String [] arrayclass = {"A","B","C","D"};
        Random random = new Random();
        int randomClass = random.nextInt(4);
        return arrayclass[randomClass];
    }
    
    private void simpanData()
    {
        nama = txtnama.getText();
        ttl = txtTtl.getText();
        jenisKelamin = cbJK.getSelectedItem().toString();
        alamat = txtalm.getText();
        programStudi = txtPs.getText();
        kelas = getRandomClass();                                 //MENGAMBIL NILAI KELAS DARI METHOD RANDOM
        nim = getIncreaseNim();
        
        try {                               
           if (nama.equals("")                                    //PERCABANGAN JIKA TEXTFIELD NAMA KOSONG
               || ttl.equals("")                                  //PERCABANGAN JIKA TEXTFIELD TTL KOSONG
               || jenisKelamin.equals("")                         //PERCABANGAN JIKA TEXTFIELD JENIS KELAMIN KOSONG
               || programStudi.equals("")                         //PERCABANGAN JIKA COMBOBOX PROGRAMSTUDI KOSONG
               || alamat.equals("")    )                          //PERCABANGAN JIKA TEXTFIELD ALAMAT KOSONG
            {
                JOptionPane.showMessageDialog
                    (this, "Data tidak boleh kosong", "error", JOptionPane.ERROR_MESSAGE);     //AKAN KELUAR TAMPILAN JOPTION ERROR
                emptyData();
            } 
            else
            {     //PERCABANGAN JIKA tidak kosong
                sql = "INSERT INTO data_mahasiswa  VALUES "               //MEMASUKKAN NILAI KE DALAM DATABASE
                        + "('"+nim+"' ,"                                 //KOLOM 1 PADA DATABASE DIAMBIL DARI INCREASENIM                           
                        + "'"+nama+"' , "                                //KOLOM 2 PADA DATABASE DIAMBIL DARI TEXTFIELD NAMA
                        + "'"+ttl+"' , "                                 //KOLOM 3 PADA DATABASE DIAMBIL DARI TEXTFIELD TTL
                        + "'"+jenisKelamin+"' , "                        //KOLOM 4 PADA DATABASE DIAMBIL DARI COMBOBOX JENISKELAMIN
                        + "'"+programStudi+"' ,"                         //KOLOM 5 PADA DATABASE DIAMBIL DARI TEXTFIELD PROGRAM STUDI
                        + "'"+alamat+"' ,"                               //KOLOM 6 PADA DATABASE DIAMBIL DARI TEXTFIELD PROGRAMSTUDI
                        + "'"+kelas+"' ,"                                //KOLOM 7 PADA DATABASE DIAMBIL DARI RANDOM KELAS
                        + "'"+getId()+"' )";                              
                conn =(Connection)Database.configDB()  ;                 //MENGKONEKSIKAN KEDATABASE DARI KELAS DATABASE METHOD CONFIGDB
                pstm = conn.prepareStatement(sql);                                           //MEMBUAT STATEMENT MYSQL
                pstm.execute();                                                              //MENGEKSEKUSI STATEMENT
                JOptionPane.showMessageDialog(null,"Registrasi Berhasil");                   //MENAMPILKAN JOPTION "REGISTRASI BERHASIL"
                toRegister();
                
            } 
        }catch(HeadlessException | SQLException e){                                              //JIKA TERJADI ERROR DALAM PENGKONEKSIAN DATABASE
          JOptionPane.showMessageDialog(this, e.getMessage());                                   //MENAMPILKAN ERRORNYA DIMANA
         } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSimpan;
    private javax.swing.JComboBox<String> cbJK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtPs;
    private javax.swing.JTextField txtTtl;
    private javax.swing.JTextField txtalm;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
