/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author WINDOWS 10
 */
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    
    public Login() {
        initComponents();
    }
    
    private int id;
    private String username;
    private String Password;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setUndecorated(true);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(54, 33, 89));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("x");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel3.setBackground(new java.awt.Color(204, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\all about kuliah\\semester 2\\Prak PBO\\UAS\\UASPPBO\\src\\uasppbo\\asset\\icons8_person_20px_1.png")); // NOI18N
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 20, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\all about kuliah\\semester 2\\Prak PBO\\UAS\\UASPPBO\\src\\uasppbo\\asset\\icons8_key_20px_2.png")); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 20, 20));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\all about kuliah\\semester 2\\Prak PBO\\UAS\\res\\Optimized-logo-removebg-preview.png")); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 100, 100));

        jLabel10.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TI's Member Information");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        txtUser.setBackground(new java.awt.Color(102, 0, 153));
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 330, 40));

        jButton3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jButton3.setText("Login!");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        txtPass.setBackground(new java.awt.Color(102, 0, 153));
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        jPanel3.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 330, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Dont have account..?");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("Sign up here");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(480, 390));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public int getId()
    {
    return id;
    }
    
    private void login(){
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }
    
    private void emptyData()
    {
        txtUser.setText("");
        txtPass.setText("");
    }
    
    
    public void checkAccount()
    {   
    username = txtUser.getText();
    Password = String.valueOf(txtPass.getPassword());
    try {
        if (username.equals("")                                                 //PERCABANGAN JIKA TEXTFIELD USERNAME KOSONG
            ||Password.equals("")) {              //ATAU JIKA TEXTFIELD PASSWORD KOSONG
        JOptionPane.showMessageDialog                                           //MAKA AKAN MENAMPILKAN JOPTION ERROR MESSAGE
        (this, "Form Login Tidak Boleh Kosong", "alert..!",                     //YANG BERISI FORM LOGIN TIDAK BOLEH KOSONG
        JOptionPane.ERROR_MESSAGE);
        }
        else{                                                                   
            String sql = "SELECT * FROM dataaccount WHERE "                     //MENGAMBIL DATA DARI DATABASE DIMANA               
                        + "Username = '"+username+"' "                 //JIKA TEXTFIELD USERNAME = DATABASE USERNAME
                        + "AND Password = "                                     //LOGIKA DAN
                        + "'"+Password+"' ";                            //JIKA TEXTFIELD PASSWORD = DATABASE PASSWORD
            java.sql.Connection conn =  (Connection)Database.configDB();        //MENGKONEKSIKAN KE DATABASE
            java.sql.Statement stm = conn.createStatement();                    //MEMBUAT STATEMENT
            java.sql.ResultSet rs = stm.executeQuery(sql);                      //MENGEKSEKUSI DATABASE KE DALAM RS
                if (rs.next()) {                                                //JIKA USERNAME DAN PASSWORD SAMA DENGAN DI DATABASE MAKA
                    id = rs.getInt("id");
                    JOptionPane.showMessageDialog
                        (null, "Login Berhasil", 
                        "succes", JOptionPane.INFORMATION_MESSAGE);             //YANG BERISI LOGIN BERHASIL
                    login();                                                  //TAMPILAN LOGIN TERTUTUP
                }else {                                                         //JIKA USERNAME DAN PASSWORD TIDAK SAMA DENGAN DI DATABASE MAKA
                    JOptionPane.showMessageDialog                               //MENAMPILKAN JOPTIONPANE
                        (this,                                                      
                        "Username atau Password salah",                         //TAMPILAN JOPTIONPANE "USERNAME ATAU PASSWORD SALAH"
                        "Login Error", JOptionPane.ERROR_MESSAGE);              //JUDUL JOPTION "LOGIN ERROR"
                    emptyData();                                                //MENGKOSONGKAN TEXTFIELD USERNAME DAN PASSWORD
                }
            }
            
        } catch (SQLException e) {                                              //JIKA TERJADI ERROR DALAM TRY
            JOptionPane.showMessageDialog(this, "Gagal Login");
            System.out.println(""+e.getMessage());
        }
    }
    
    public void toRegiter()
    {
        Form_Registrasi form_register = new Form_Registrasi();
        form_register.setVisible(true);
        this.dispose();
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        checkAccount();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        toRegiter();
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
